add_executable(arbreplay_smoke_test smoke_test.cpp)
target_link_libraries(arbreplay_smoke_test PRIVATE arbreplay_project_options)
add_test(NAME arbreplay_smoke_test COMMAND arbreplay_smoke_test)

add_executable(arbreplay_price_test price_test.cpp)
target_link_libraries(arbreplay_price_test PRIVATE arbreplay_project_options)
add_test(NAME arbreplay_price_test COMMAND arbreplay_price_test)

add_executable(arbreplay_quantity_test quantity_test.cpp)
target_link_libraries(arbreplay_quantity_test PRIVATE arbreplay_project_options)
add_test(NAME arbreplay_quantity_test COMMAND arbreplay_quantity_test)

add_executable(arbreplay_book_level_test book_level_test.cpp)
target_link_libraries(arbreplay_book_level_test PRIVATE arbreplay_project_options)
add_test(NAME arbreplay_book_level_test COMMAND arbreplay_book_level_test)

add_executable(arbreplay_book_side_test book_side_test.cpp)
target_link_libraries(arbreplay_book_side_test PRIVATE arbreplay)
add_test(NAME arbreplay_book_side_test COMMAND arbreplay_book_side_test)

add_executable(arbreplay_outcome_book_test outcome_book_test.cpp)
target_link_libraries(arbreplay_outcome_book_test PRIVATE arbreplay)
add_test(NAME arbreplay_outcome_book_test COMMAND arbreplay_outcome_book_test)

add_executable(arbreplay_outcome_id_test outcome_id_test.cpp)
target_link_libraries(arbreplay_outcome_id_test PRIVATE arbreplay)
add_test(NAME arbreplay_outcome_id_test COMMAND arbreplay_outcome_id_test)

add_executable(arbreplay_market_test market_test.cpp)
target_link_libraries(arbreplay_market_test PRIVATE arbreplay)
add_test(NAME arbreplay_market_test COMMAND arbreplay_market_test)

add_executable(arbreplay_money_test money_test.cpp)
target_link_libraries(arbreplay_money_test PRIVATE arbreplay)
add_test(NAME arbreplay_money_test COMMAND arbreplay_money_test)
